AppBundle\Entity\Distributor:
    type: entity
    repositoryClass: AppBundle\Entity\DistributorRepository
    table: distributor
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            nullable: true
        country:
            type: string
            length: 100
    oneToMany:
        albums:
            targetEntity: Album
            mappedBy: distributor