AppBundle\Entity\Genre:
    type: entity
    repositoryClass: AppBundle\Entity\GenreRepository
    table: genre
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name_pl:
            type: string
            length: 100
            nullable: true
        name_en:
            type: string
            length: 100
            nullable: true
    manyToMany:
        albums:
            targetEntity: Album
            mappedBy: genres
