AppBundle\Entity\Gentre:
    type: entity
    repositoryClass: AppBundle\Entity\GentreRepository
    table: gentre
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            nullable: true
    manyToMany:
        albums:
            targetEntity: Album
            mappedBy: gentres
