AppBundle\Entity\Track:
    type: entity
    repositoryClass: AppBundle\Entity\TrackRepository
    table: track
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        number:
            type: integer
    manyToOne:
        album:
            targetEntity: Album
            joinColumn:
                name: album_id
                referencedColumnName: id