<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function findAll($filter = null, $search = '')
    {
        $entityManager = $this->getEntityManager();
        $queryBuilder = $entityManager
            ->getRepository('AppBundle:Album')
            ->createQueryBuilder('a');

        if ($search) {
            $queryBuilder = $queryBuilder
                ->where('a.title LIKE :criteria')
                ->setParameter('criteria', '%' . $search . '%');
        }

        if ($filter) {
            $filter = explode(',', $filter);
            foreach ($filter as $f) {
                $tmp = explode(' ', $f);
                $queryBuilder = $queryBuilder->orderBy('a.' . $tmp[0], $tmp[1]);
            }
        } else {
            $queryBuilder = $queryBuilder->orderBy('a.title','ASC');
        }

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
