<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function findAll($filter = null, $search = '')
    {
        $entityManager = $this->getEntityManager();
        $queryBuilder = $entityManager
            ->getRepository('AppBundle:Artist')
            ->createQueryBuilder('a');

        if ($search) {
            $queryBuilder = $queryBuilder
                ->where('a.firstname LIKE :criteria')
                ->orWhere('a.lastname LIKE :criteria')
                ->orWhere('a.name LIKE :criteria')
                ->setParameter('criteria', '%' . $search . '%');
        }

        if ($filter) {
            $filter = explode(',', $filter);
            foreach ($filter as $f) {
                $tmp = explode(' ', $f);
                $queryBuilder = $queryBuilder->orderBy('a.' . $tmp[0], $tmp[1]);
            }
        } else {
            $queryBuilder = $queryBuilder
                ->orderBy('a.name','ASC')
                ->orderBy('a.lastname','ASC');
        }

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
