<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function findAll($filter = null)
    {
        if ($filter) {
            $filter = explode(',', $filter);
            $fl = [];
            foreach ($filter as $f) {
                $tmp = explode(' ', $f);
                $fl[$tmp[0]] = $tmp[1];
            }
            return $this->findBy([], $fl);
        } else {
            return $this->findBy([], ['name' => 'ASC', 'lastname' => 'ASC']);
        }
    }
}
