<?php

namespace AppBundle\Entity;

/**
 * GentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GentreRepository extends \Doctrine\ORM\EntityRepository
{
}
